### PR TITLE
Two new analog watchfaces for GTR 2

### PR DESCRIPTION
**Pull request by hibrice**
Hi,

Here are two analog WF for GTR 2. I hope you like it.

Best regards,
Brice

### CODE REVIEW

**Comment by twinko** [comment]
@hibrice awesome, was alway looking to create a analog one but never finished them! Could you please add the gif from the WF-Maker so we have a consistant readme file?

**Comment by hibrice** [comment]
Hi I've added previews !

**Comment by twinko** [comment]
ah damn there is a typo in the directory..... whatever :D "CTR"
One more Question is the graph included in the AOD (always on Display)?

*edit changed directory name

**Comment by hibrice** [comment]
Damned. Sorry for the typo !

There is no graph. They are minimal  watchfaces for casual hangout 😀

If people wants graph and lots of informations I think they'll go for a digit watchface.

**Comment by hibrice** [comment]
Images links are broken cause of the typo. I'll fixe this tonight.

**Comment by twinko** [comment]
HEy no worries, fixed it and added the info for no AOD.
Thank you so much for these great watchfaces :)

**Comment by hibrice** [comment]
Thanks @twinko I've just realise I might not understood you well. In AOD, there is glucoce data but no graph for both WF.

I'll try to make other WFs, this time i'll make sure everthing is right.

**Comment by twinko** [comment]
ah ok i understand, no worries and thank looking forward to your next watchfaces :)

**Pull request merged**
